version: '3.8'

services:
  # python service for data generation
  generator:
    build:
      context: .
      dockerfile: docker/Dockerfile.generator
    env_file: .env
    volumes:
      - ./data_generator/data:/app/data

  # infra cleanup service
  #infra-cleanup:
  #  build:
  #    context: .
  #    dockerfile: docker/Dockerfile.infra_cleanup
  #  env_file: .env
  #  volumes:
  #    - ./infra_cleanup:/app/infra_cleanup
  #  depends_on:
  #    - generator
