version: '3.8'

services:

  # OpenTelemetry Collector for receiving and exporting telemetry data
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "4318:4318"   # OTLP HTTP receiver


  # python service for data generation
  generator:
    build:
      context: .
      dockerfile: docker/Dockerfile.generator
    env_file: .env
    volumes:
      - ./data_generator/data:/app/data

      
  # infra cleanup service
  #infra-cleanup:
  #  build:
  #    context: .
  #    dockerfile: docker/Dockerfile.infra_cleanup
  #  env_file: .env
  #  volumes:
  #    - ./infra_cleanup:/app/infra_cleanup
  #  depends_on:
  #    - generator
